//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymXchange.Service.Info
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.symxchange.generated.symitar.com/episysinformation", ConfigurationName="SymXchange.Service.Info.EpisysInformationService")]
    public partial interface EpisysInformationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.symxchange.generated.symitar.com/episysinformation/getGeneralEpisysInf" +
            "ormation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SymXchange.Service.Info.getGeneralEpisysInformationResponse> getGeneralEpisysInformationAsync(SymXchange.Service.Info.getGeneralEpisysInformationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.symxchange.generated.symitar.com/episysinformation/dto")]
    public partial class GeneralEpisysInformationRequest
    {
        
        private AdminCredentialsChoice credentialsField;
        
        private DeviceInformation deviceInformationField;
        
        private string messageIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AdminCredentialsChoice Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DeviceInformation DeviceInformation
        {
            get
            {
                return this.deviceInformationField;
            }
            set
            {
                this.deviceInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.symxchange.generated.symitar.com/common/dto/common")]
        public string MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.symxchange.generated.symitar.com/common/dto/common")]
    public partial class AdminCredentialsChoice
    {
        
        private object itemField;
        
        private short processorUserField;
        
        private bool processorUserFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdministrativeCredentials", typeof(AdministrativeCredentials), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TokenCredentials", typeof(TokenCredentials), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UserNumberCredentials", typeof(UserNumberCredentials), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public short ProcessorUser
        {
            get
            {
                return this.processorUserField;
            }
            set
            {
                this.processorUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProcessorUserSpecified
        {
            get
            {
                return this.processorUserFieldSpecified;
            }
            set
            {
                this.processorUserFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.symxchange.generated.symitar.com/common/dto/common")]
    public partial class AdministrativeCredentials
    {
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.symxchange.generated.symitar.com/common/dto/common")]
    public partial class Status
    {
        
        private int statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusCodeSpecified
        {
            get
            {
                return this.statusCodeFieldSpecified;
            }
            set
            {
                this.statusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.symxchange.generated.symitar.com/episysinformation/dto")]
    public partial class GeneralEpisysInformationResponse
    {
        
        private System.DateTime operatingSystemDateTimeField;
        
        private bool operatingSystemDateTimeFieldSpecified;
        
        private System.DateTime businessDateTimeField;
        
        private bool businessDateTimeFieldSpecified;
        
        private System.DateTime previousBusinessDateField;
        
        private bool previousBusinessDateFieldSpecified;
        
        private string operatingSystemHostNameField;
        
        private short institutionNumberField;
        
        private bool institutionNumberFieldSpecified;
        
        private short symNumberField;
        
        private bool symNumberFieldSpecified;
        
        private string symXchangeInstanceNameField;
        
        private short symXchangeClientNumberField;
        
        private bool symXchangeClientNumberFieldSpecified;
        
        private bool inMemoModeField;
        
        private bool inMemoModeFieldSpecified;
        
        private string episysVersionField;
        
        private short episysServicePackField;
        
        private bool episysServicePackFieldSpecified;
        
        private bool isEpisysAlphaReleaseField;
        
        private bool isEpisysAlphaReleaseFieldSpecified;
        
        private bool isEpisysBetaReleaseField;
        
        private bool isEpisysBetaReleaseFieldSpecified;
        
        private bool isEpisysPreReleaseField;
        
        private bool isEpisysPreReleaseFieldSpecified;
        
        private string episysQuestVersionField;
        
        private short symXChangeInstanceIdField;
        
        private bool symXChangeInstanceIdFieldSpecified;
        
        private System.DateTime symXChangeLastOnHostDateTimeField;
        
        private bool symXChangeLastOnHostDateTimeFieldSpecified;
        
        private Status statusField;
        
        private string messageIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime OperatingSystemDateTime
        {
            get
            {
                return this.operatingSystemDateTimeField;
            }
            set
            {
                this.operatingSystemDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperatingSystemDateTimeSpecified
        {
            get
            {
                return this.operatingSystemDateTimeFieldSpecified;
            }
            set
            {
                this.operatingSystemDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime BusinessDateTime
        {
            get
            {
                return this.businessDateTimeField;
            }
            set
            {
                this.businessDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BusinessDateTimeSpecified
        {
            get
            {
                return this.businessDateTimeFieldSpecified;
            }
            set
            {
                this.businessDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime PreviousBusinessDate
        {
            get
            {
                return this.previousBusinessDateField;
            }
            set
            {
                this.previousBusinessDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreviousBusinessDateSpecified
        {
            get
            {
                return this.previousBusinessDateFieldSpecified;
            }
            set
            {
                this.previousBusinessDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string OperatingSystemHostName
        {
            get
            {
                return this.operatingSystemHostNameField;
            }
            set
            {
                this.operatingSystemHostNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public short InstitutionNumber
        {
            get
            {
                return this.institutionNumberField;
            }
            set
            {
                this.institutionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstitutionNumberSpecified
        {
            get
            {
                return this.institutionNumberFieldSpecified;
            }
            set
            {
                this.institutionNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public short SymNumber
        {
            get
            {
                return this.symNumberField;
            }
            set
            {
                this.symNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SymNumberSpecified
        {
            get
            {
                return this.symNumberFieldSpecified;
            }
            set
            {
                this.symNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SymXchangeInstanceName
        {
            get
            {
                return this.symXchangeInstanceNameField;
            }
            set
            {
                this.symXchangeInstanceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public short SymXchangeClientNumber
        {
            get
            {
                return this.symXchangeClientNumberField;
            }
            set
            {
                this.symXchangeClientNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SymXchangeClientNumberSpecified
        {
            get
            {
                return this.symXchangeClientNumberFieldSpecified;
            }
            set
            {
                this.symXchangeClientNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool InMemoMode
        {
            get
            {
                return this.inMemoModeField;
            }
            set
            {
                this.inMemoModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InMemoModeSpecified
        {
            get
            {
                return this.inMemoModeFieldSpecified;
            }
            set
            {
                this.inMemoModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string EpisysVersion
        {
            get
            {
                return this.episysVersionField;
            }
            set
            {
                this.episysVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public short EpisysServicePack
        {
            get
            {
                return this.episysServicePackField;
            }
            set
            {
                this.episysServicePackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EpisysServicePackSpecified
        {
            get
            {
                return this.episysServicePackFieldSpecified;
            }
            set
            {
                this.episysServicePackFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public bool IsEpisysAlphaRelease
        {
            get
            {
                return this.isEpisysAlphaReleaseField;
            }
            set
            {
                this.isEpisysAlphaReleaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsEpisysAlphaReleaseSpecified
        {
            get
            {
                return this.isEpisysAlphaReleaseFieldSpecified;
            }
            set
            {
                this.isEpisysAlphaReleaseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public bool IsEpisysBetaRelease
        {
            get
            {
                return this.isEpisysBetaReleaseField;
            }
            set
            {
                this.isEpisysBetaReleaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsEpisysBetaReleaseSpecified
        {
            get
            {
                return this.isEpisysBetaReleaseFieldSpecified;
            }
            set
            {
                this.isEpisysBetaReleaseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool IsEpisysPreRelease
        {
            get
            {
                return this.isEpisysPreReleaseField;
            }
            set
            {
                this.isEpisysPreReleaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsEpisysPreReleaseSpecified
        {
            get
            {
                return this.isEpisysPreReleaseFieldSpecified;
            }
            set
            {
                this.isEpisysPreReleaseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string EpisysQuestVersion
        {
            get
            {
                return this.episysQuestVersionField;
            }
            set
            {
                this.episysQuestVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public short SymXChangeInstanceId
        {
            get
            {
                return this.symXChangeInstanceIdField;
            }
            set
            {
                this.symXChangeInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SymXChangeInstanceIdSpecified
        {
            get
            {
                return this.symXChangeInstanceIdFieldSpecified;
            }
            set
            {
                this.symXChangeInstanceIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public System.DateTime SymXChangeLastOnHostDateTime
        {
            get
            {
                return this.symXChangeLastOnHostDateTimeField;
            }
            set
            {
                this.symXChangeLastOnHostDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SymXChangeLastOnHostDateTimeSpecified
        {
            get
            {
                return this.symXChangeLastOnHostDateTimeFieldSpecified;
            }
            set
            {
                this.symXChangeLastOnHostDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.symxchange.generated.symitar.com/common/dto/common")]
        public string MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.symxchange.generated.symitar.com/common/dto/common")]
    public partial class DeviceInformation
    {
        
        private string deviceTypeField;
        
        private short deviceNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DeviceType
        {
            get
            {
                return this.deviceTypeField;
            }
            set
            {
                this.deviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short DeviceNumber
        {
            get
            {
                return this.deviceNumberField;
            }
            set
            {
                this.deviceNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.symxchange.generated.symitar.com/common/dto/common")]
    public partial class TokenCredentials
    {
        
        private string tokenIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TokenId
        {
            get
            {
                return this.tokenIdField;
            }
            set
            {
                this.tokenIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.symxchange.generated.symitar.com/common/dto/common")]
    public partial class UserNumberCredentials
    {
        
        private short userNumberField;
        
        private bool userNumberFieldSpecified;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public short UserNumber
        {
            get
            {
                return this.userNumberField;
            }
            set
            {
                this.userNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserNumberSpecified
        {
            get
            {
                return this.userNumberFieldSpecified;
            }
            set
            {
                this.userNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGeneralEpisysInformation", WrapperNamespace="http://www.symxchange.generated.symitar.com/episysinformation", IsWrapped=true)]
    public partial class getGeneralEpisysInformationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.symxchange.generated.symitar.com/episysinformation", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SymXchange.Service.Info.GeneralEpisysInformationRequest Request;
        
        public getGeneralEpisysInformationRequest()
        {
        }
        
        public getGeneralEpisysInformationRequest(SymXchange.Service.Info.GeneralEpisysInformationRequest Request)
        {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGeneralEpisysInformationResponse", WrapperNamespace="http://www.symxchange.generated.symitar.com/episysinformation", IsWrapped=true)]
    public partial class getGeneralEpisysInformationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.symxchange.generated.symitar.com/episysinformation", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SymXchange.Service.Info.GeneralEpisysInformationResponse Response;
        
        public getGeneralEpisysInformationResponse()
        {
        }
        
        public getGeneralEpisysInformationResponse(SymXchange.Service.Info.GeneralEpisysInformationResponse Response)
        {
            this.Response = Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface EpisysInformationServiceChannel : SymXchange.Service.Info.EpisysInformationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class EpisysInformationServiceClient : System.ServiceModel.ClientBase<SymXchange.Service.Info.EpisysInformationService>, SymXchange.Service.Info.EpisysInformationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EpisysInformationServiceClient() : 
                base(EpisysInformationServiceClient.GetDefaultBinding(), EpisysInformationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EpisysInformationServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EpisysInformationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EpisysInformationServiceClient.GetBindingForEndpoint(endpointConfiguration), EpisysInformationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EpisysInformationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EpisysInformationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EpisysInformationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EpisysInformationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EpisysInformationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SymXchange.Service.Info.getGeneralEpisysInformationResponse> SymXchange.Service.Info.EpisysInformationService.getGeneralEpisysInformationAsync(SymXchange.Service.Info.getGeneralEpisysInformationRequest request)
        {
            return base.Channel.getGeneralEpisysInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SymXchange.Service.Info.getGeneralEpisysInformationResponse> getGeneralEpisysInformationAsync(SymXchange.Service.Info.GeneralEpisysInformationRequest Request)
        {
            SymXchange.Service.Info.getGeneralEpisysInformationRequest inValue = new SymXchange.Service.Info.getGeneralEpisysInformationRequest();
            inValue.Request = Request;
            return ((SymXchange.Service.Info.EpisysInformationService)(this)).getGeneralEpisysInformationAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EpisysInformationServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EpisysInformationServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.24.69.24:8088/SymXchange/2020.01/episysinformation");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EpisysInformationServiceClient.GetBindingForEndpoint(EndpointConfiguration.EpisysInformationServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EpisysInformationServiceClient.GetEndpointAddress(EndpointConfiguration.EpisysInformationServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            EpisysInformationServicePort,
        }
    }
}
